In [23]:
import numpy as np

In [24]:
def find_b(A, x_acc=np.array([None])):  # находим b
    if x_acc[0] is None:
        x_acc = np.random.uniform(-100, 100, size=A.shape[0])  # задаем случайные значения для x_acc, если он не задан
    b = np.dot(A, x_acc)
    return b, x_acc

In [25]:
def cond(A):  # находим числа обусловленности
    v0 = 1
    mult = np.zeros(A.shape[0])
    cond_s = np.dot(np.linalg.norm(A), np.linalg.norm(np.linalg.inv(A)))  # Спектральный критерий
    for i in range(A.shape[0]):
        v0 *= np.linalg.norm(A[i])
    cond_v = v0 / abs(np.linalg.det(A))  # Объемный критерий
    C = np.linalg.inv(A)
    for i in range(A.shape[0]):
        mult[i] = np.linalg.norm(A[i]) * np.linalg.norm(C[:, i])
    cond_a = max(mult)  # Угловой критерий
    return cond_s, cond_v, cond_a


In [26]:
def varied_matrix(A, b):  # варьируем матрицу и b
    k = 0
    x_app = np.zeros((3, A.shape[0]))
    for i in (-2, -5, -8):
        A_app = A - 10 ** i
        b_app = b - 10 ** i
        for j in range(A.shape[0]):
            x_app[k] = np.linalg.solve(A_app, b_app)
        k += 1
    return x_app

In [27]:
def print_matrix(A, x_acc, x_app):
    print("Матрица:")
    print(*A, sep='\n')
    print()
    print("Точное решение:")
    for elem in x_acc:
        print('|{:12.8f}'.format(elem), '|')
    print()
    print("Числа обусловленности:")
    print("    Спектральный критерий обусловленности:", cond_s)
    print("    Объемный критерий(критерий Ортеги):", cond_v)
    print("    Угловой критерий:", cond_a)
    print()
    k = 0
    for i in (-2, -5, -8):
        print("eps = 10^({}):".format(i))
        print("    Приближенное решение:")
        for elem in x_app[k]:
            print("   ", '|{:16.8f}'.format(elem), '|')
        print("    Невязка:")
        for elem in abs(x_acc - x_app[k]):
            print("   ", '|{:16.12f}'.format(elem), '|')
        k += 1
    print()

In [28]:
data_1 = [[-400.60, 199.80],
          [1198.80, -600.40]]
data_2 = [[-402.50, 200.50],
          [1203.00, -603.00]]
data_Hilbert4 = [[1.0000, 0.5000, 0.3333, 0.2500],
                 [0.5000, 0.3333, 0.2500, 0.2000],
                 [0.3333, 0.2500, 0.2000, 0.1667],
                 [0.2500, 0.2000, 0.1667, 0.1429]]
data_Hilbert5 = [[1.0000, 0.5000, 0.3333, 0.2500, 0.2000],
                 [0.5000, 0.3333, 0.2500, 0.2000, 0.1667],
                 [0.3333, 0.2500, 0.2000, 0.1667, 0.1429],
                 [0.2500, 0.2000, 0.1667, 0.1429, 0.1250],
                 [0.2000, 0.1667, 0.1429, 0.1250, 0.1111]]
data_diag = [[5, -1, 0, 0, 0, 0],
             [-1, 5, -1, 0, 0, 0],
             [0, -1, 5, -1, 0, 0],
             [0, 0, -1, 5, -1, 0],
             [0, 0, 0, -1, 5, -1],
             [0, 0, 0, 0, -1, 5]]
data_rand = [[1, 5],
             [2, 4.1]]

In [29]:
A = np.array(data_1, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[-400.6  199.8]
[1198.8 -600.4]

Точное решение:
|-68.95543917 |
|  4.18152138 |

Числа обусловленности:
    Спектральный критерий обусловленности: 1998.0020000000293
    Объемный критерий(критерий Ортеги): 600.200033056189
    Угловой критерий: 600.2000330561891

eps = 10^(-2):
    Приближенное решение:
    |    -68.44144996 |
    |      5.20885747 |
    Невязка:
    |  0.513989205135 |
    |  1.027336084345 |
eps = 10^(-5):
    Приближенное решение:
    |    -68.95491286 |
    |      4.18257335 |
    Невязка:
    |  0.000526310261 |
    |  0.001051962798 |
eps = 10^(-8):
    Приближенное решение:
    |    -68.95543864 |
    |      4.18152244 |
    Невязка:
    |  0.000000526322 |
    |  0.000001051987 |



In [30]:
A = np.array(data_2, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[-402.5  200.5]
[1203. -603.]

Точное решение:
| 10.90093092 |
| 74.48394092 |

Числа обусловленности:
    Спектральный критерий обусловленности: 1336.6696547144766
    Объемный критерий(критерий Ортеги): 401.80004918285067
    Угловой критерий: 401.80004918285056

eps = 10^(-2):
    Приближенное решение:
    |     10.45779853 |
    |     73.59850338 |
    Невязка:
    |  0.443132394316 |
    |  0.885437534629 |
eps = 10^(-5):
    Приближенное решение:
    |     10.90048071 |
    |     74.48304133 |
    Невязка:
    |  0.000450213546 |
    |  0.000899586619 |
eps = 10^(-8):
    Приближенное решение:
    |     10.90093047 |
    |     74.48394002 |
    Невязка:
    |  0.000000450221 |
    |  0.000000899602 |



In [31]:
A = np.array(data_Hilbert4, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[1.     0.5    0.3333 0.25  ]
[0.5    0.3333 0.25   0.2   ]
[0.3333 0.25   0.2    0.1667]
[0.25   0.2    0.1667 0.1429]

Точное решение:
|-37.15121457 |
|-97.25580550 |
| 49.08253434 |
| 44.79068448 |

Числа обусловленности:
    Спектральный критерий обусловленности: 19935.102739219066
    Объемный критерий(критерий Ортеги): 1195831.4125881186
    Угловой критерий: 5134.809152553534

eps = 10^(-2):
    Приближенное решение:
    |    -34.18839361 |
    |   -137.70338206 |
    |    163.83274079 |
    |    -41.15914883 |
    Невязка:
    |  2.962820962656 |
    | 40.447576563667 |
    |114.750206455795 |
    | 85.949833318651 |
eps = 10^(-5):
    Приближенное решение:
    |    -37.14876370 |
    |    -97.28926414 |
    |     49.17745686 |
    |     44.71958592 |
    Невязка:
    |  0.002450875206 |
    |  0.033458640866 |
    |  0.094922521279 |
    |  0.071098563863 |
eps = 10^(-8):
    Приближенное решение:
    |    -37.15121212 |
    |    -97.25583895 |
    |     49.08262924 |

In [32]:
A = np.array(data_Hilbert5, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[1.     0.5    0.3333 0.25   0.2   ]
[0.5    0.3333 0.25   0.2    0.1667]
[0.3333 0.25   0.2    0.1667 0.1429]
[0.25   0.2    0.1667 0.1429 0.125 ]
[0.2    0.1667 0.1429 0.125  0.1111]

Точное решение:
| 67.65671457 |
| 70.05448842 |
|-23.27046662 |
|-94.41917920 |
| -8.39709395 |

Числа обусловленности:
    Спектральный критерий обусловленности: 138544.7922004316
    Объемный критерий(критерий Ортеги): 4851435259.65631
    Угловой критерий: 26519.459242141937

eps = 10^(-2):
    Приближенное решение:
    |     67.24007720 |
    |     74.72337667 |
    |    -29.25110326 |
    |   -107.09787165 |
    |      8.48388710 |
    Невязка:
    |  0.416637371929 |
    |  4.668888247798 |
    |  5.980636635894 |
    | 12.678692445997 |
    | 16.880981054850 |
eps = 10^(-5):
    Приближенное решение:
    |     67.65637656 |
    |     70.05827621 |
    |    -23.27531861 |
    |    -94.42946520 |
    |     -8.38339871 |
    Невязка:
    |  0.000338010450 |
    |  0.003787785545 |
    |  0.

In [33]:
A = np.array(data_diag, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[ 5. -1.  0.  0.  0.  0.]
[-1.  5. -1.  0.  0.  0.]
[ 0. -1.  5. -1.  0.  0.]
[ 0.  0. -1.  5. -1.  0.]
[ 0.  0.  0. -1.  5. -1.]
[ 0.  0.  0.  0. -1.  5.]

Точное решение:
| 99.86035915 |
| 58.50128667 |
|  3.42406007 |
| 52.03881423 |
|-60.97055396 |
| -1.41917757 |

Числа обусловленности:
    Спектральный критерий обусловленности: 6.904338920218347
    Объемный критерий(критерий Ортеги): 1.4984583761562187
    Угловой критерий: 1.1840750036739822

eps = 10^(-2):
    Приближенное решение:
    |    100.26448216 |
    |     58.98960197 |
    |      3.92921382 |
    |     52.54396799 |
    |    -60.48223866 |
    |     -1.01505457 |
    Невязка:
    |  0.404123004959 |
    |  0.488315297659 |
    |  0.505153756199 |
    |  0.505153756199 |
    |  0.488315297659 |
    |  0.404123004959 |
eps = 10^(-5):
    Приближенное решение:
    |     99.86075591 |
    |     58.50176609 |
    |      3.42455601 |
    |     52.03931018 |
    |    -60.97007454 |
    |     -1.41878081 |
    Невяз

In [34]:
A = np.array(data_rand, dtype=float)
b, x_acc = find_b(A)
cond_s, cond_v, cond_a = cond(A)
x_app = varied_matrix(A, b)
print_matrix(A, x_acc, x_app)

Матрица:
[1. 5.]
[2.  4.1]

Точное решение:
|-34.63029599 |
| 74.52836875 |

Числа обусловленности:
    Спектральный критерий обусловленности: 7.933898305084745
    Объемный критерий(критерий Ортеги): 3.9424909261368812
    Угловой критерий: 3.9424909261368812

eps = 10^(-2):
    Приближенное решение:
    |    -34.57076825 |
    |     74.59451068 |
    Невязка:
    |  0.059527742696 |
    |  0.066141936328 |
eps = 10^(-5):
    Приближенное решение:
    |    -34.63023666 |
    |     74.52843468 |
    Невязка:
    |  0.000059336234 |
    |  0.000065929149 |
eps = 10^(-8):
    Приближенное решение:
    |    -34.63029593 |
    |     74.52836881 |
    Невязка:
    |  0.000000059336 |
    |  0.000000065929 |

