In [19]:
import numpy as np

In [20]:
def find_b(A, x):  # находим b
    b = np.dot(A, x)
    return b

In [21]:
def find_coef(A, b):  # находим alpha и beta
    alpha = np.array(np.zeros((A.shape[0], A.shape[0])))
    beta = np.array(np.zeros(b.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[0]):
            if i != j:
                alpha[i][j] = - A[i][j] / A[i][i]
                beta[i] = b[i] / A[i][i]
            else:
                alpha[i][i] = 0
    return alpha, beta

In [52]:
def iteration_method(alpha, beta, x, eps, iter=1):  # метод простой итерации
    err = eps + 1
    while err > eps:
        err = np.linalg.norm(np.dot(alpha, x) + beta - x)
        x = np.dot(alpha, x) + beta
        iter += 1
    x = np.dot(alpha, x) + beta
    return x, iter


In [34]:
def Zeidel_method(A, b, eps):  # метод Зейделя
    iter = 0
    x = np.array(np.zeros((b.shape[0])))
    err = eps + 1
    while err > eps:
        x_new = x.copy()
        for i in range(A.shape[0]):
            x1 = sum(A[i][j] * x_new[j] for j in range(i))
            x2 = sum(A[i][j] * x[j] for j in range(i + 1, A.shape[0]))
            x_new[i] = (b[i] - x1 - x2)/A[i][i]
        err = np.linalg.norm(x_new - x)
        iter += 
        x = x_new
    return x, iter

In [54]:
for n in (2, 3):
    A = np.array(np.zeros((n, n)), dtype=float)
    x = np.random.uniform(0, 100, size=A.shape[0])
    for i in range(n):
        for j in range(n):
            A[i][j] = 1 / (i + 1 + j)
    b = find_b(A, x)
    alpha, beta = find_coef(A, b)
    for eps in (1e-4, 1e-7, 1e-10, 1e-13):
        print("Матрица Гилберта:", n, "порядка:")
        print(*A, sep='\n')
        print("Погрешность:", eps)
        print("Методе простой итерации:")
        print("   Количество итераций:", iteration_method(alpha, beta, beta, eps)[1])
        print("   ||x - x_a||:", np.linalg.norm(x - iteration_method(alpha, beta, beta, eps)[0]))
        print()
        print("Метод Зейделя:")
        print("   Количество итераций:", seidel_method(A, b, eps)[1])
        print("   ||x - x_a||:", np.linalg.norm(x - seidel_method(A, b, eps)[0]))
        print("----------------------------------------------------------------------------------------------")

Матрица Гилберта: 2 порядка:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 0.0001
Методе простой итерации:
   Количество итераций: 95
   ||x - x_a||: 5.565493150962482e-05

Метод Зейделя:
   Количество итераций: 43
   ||x - x_a||: 0.00028104411581073756
----------------------------------------------------------------------------------------------
Матрица Гилберта: 2 порядка:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 1e-07
Методе простой итерации:
   Количество итераций: 143
   ||x - x_a||: 5.5843698810251815e-08

Метод Зейделя:
   Количество итераций: 67
   ||x - x_a||: 2.8199724292069004e-07
----------------------------------------------------------------------------------------------
Матрица Гилберта: 2 порядка:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 1e-10
Методе простой итерации:
   Количество итераций: 191
   ||x - x_a||: 5.606127700933749e-11

Метод Зейделя:
   Количество итераций: 91
   ||x - x_a||: 2.829774291459615e-10
---------------------------------------------

<ipython-input-52-a4ffc18bc7cd>:4: RuntimeWarning: overflow encountered in subtract
  err = np.linalg.norm(np.dot(alpha, x) + beta - x)



   ||x - x_a||: 0.005085072185878196
----------------------------------------------------------------------------------------------
Матрица Гилберта: 3 порядка:
[1.         0.5        0.33333333]
[0.5        0.33333333 0.25      ]
[0.33333333 0.25       0.2       ]
Погрешность: 1e-07
Методе простой итерации:
   Количество итераций: 1299
   ||x - x_a||: nan

Метод Зейделя:
   Количество итераций: 854
   ||x - x_a||: 5.028544752715526e-06
----------------------------------------------------------------------------------------------
Матрица Гилберта: 3 порядка:
[1.         0.5        0.33333333]
[0.5        0.33333333 0.25      ]
[0.33333333 0.25       0.2       ]
Погрешность: 1e-10
Методе простой итерации:
   Количество итераций: 1299
   ||x - x_a||: nan

Метод Зейделя:
   Количество итераций: 1211
   ||x - x_a||: 5.069756495865053e-09
----------------------------------------------------------------------------------------------
Матрица Гилберта: 3 порядка:
[1.         0.5        0.3333

In [43]:
data_1 = [[-400.60, 199.80],
          [1198.80, -600.40]]
data_2 = [[-402.50, 200.50],
          [1203.00, -603.00]]
data_diag = [[20, 3, -1],
             [1, 50, 1],
             [1, 3, 40]]


In [47]:
A = np.array(data_1, dtype=float)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
alpha, beta = find_coef(A, b)
for eps in (1e-4, 1e-7, 1e-10, 1e-13):
    print("Матрица из методички А.Н.Пакулиной:")
    print(*A, sep='\n')
    print("Погрешность:", eps)
    print("Методе простой итерации:")
    print("   Количество итераций:", iteration_method(alpha, beta, beta, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - iteration_method(alpha, beta, beta, eps)[0]))
    print()
    print("Метод Зейделя:")
    print("   Количество итераций:", seidel_method(A, b, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - seidel_method(A, b, eps)[0]))
    print("----------------------------------------------------------------------------------------------")

Матрица из методички А.Н.Пакулиной:
[-400.6  199.8]
[1198.8 -600.4]
Погрешность: 0.0001
Методе простой итерации:
   Количество итераций: 6879
   ||x - x_a||: 5.3414349094554696e-05

Метод Зейделя:
   Количество итераций: 1680
   ||x - x_a||: 0.02386485883860471
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[-400.6  199.8]
[1198.8 -600.4]
Погрешность: 1e-07
Методе простой итерации:
   Количество итераций: 10195
   ||x - x_a||: 5.3417468973934316e-08

Метод Зейделя:
   Количество итераций: 3338
   ||x - x_a||: 2.3864732573494895e-05
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[-400.6  199.8]
[1198.8 -600.4]
Погрешность: 1e-10
Методе простой итерации:
   Количество итераций: 13511
   ||x - x_a||: 5.698676774337688e-11

Метод Зейделя:
   Количество итераций: 4996
   ||x - x_a||: 2.3869699093645843e-08
-------------------

In [45]:
A = np.array(data_2, dtype=float)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
alpha, beta = find_coef(A, b)
for eps in (1e-4, 1e-7, 1e-10, 1e-13):
    print("Матрица из методички А.Н.Пакулиной:")
    print(*A, sep='\n')
    print("Погрешность:", eps)
    print("Методе простой итерации:")
    print("   Количество итераций:", iteration_method(alpha, beta, beta, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - iteration_method(alpha, beta, beta, eps)[0]))
    print()
    print("Метод Зейделя:")
    print("   Количество итераций:", seidel_method(A, b, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - seidel_method(A, b, eps)[0]))
    print("----------------------------------------------------------------------------------------------")

Матрица из методички А.Н.Пакулиной:
[-402.5  200.5]
[1203. -603.]
Погрешность: 0.0001
Методе простой итерации:
   Количество итераций: 3654
   ||x - x_a||: 0.0006107398477275855

Метод Зейделя:
   Количество итераций: 1323
   ||x - x_a||: 0.01594831991560259
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[-402.5  200.5]
[1203. -603.]
Погрешность: 1e-07
Методе простой итерации:
   Количество итераций: 5874
   ||x - x_a||: 6.099763140113674e-07

Метод Зейделя:
   Количество итераций: 2433
   ||x - x_a||: 1.5928365943079107e-05
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[-402.5  200.5]
[1203. -603.]
Погрешность: 1e-10
Методе простой итерации:
   Количество итераций: 8094
   ||x - x_a||: 6.098637612168445e-10

Метод Зейделя:
   Количество итераций: 3542
   ||x - x_a||: 1.60082509076571e-08
-------------------------------

In [46]:
A = np.array(data_diag, dtype=float)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
alpha, beta = find_coef(A, b)
for eps in (1e-4, 1e-7, 1e-10, 1e-13):
    print("Матрица из методички А.Н.Пакулиной:")
    print(*A, sep='\n')
    print("Погрешность:", eps)
    print("Методе простой итерации:")
    print("   Количество итераций:", iteration_method(alpha, beta, beta, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - iteration_method(alpha, beta, beta, eps)[0]))
    print()
    print("Метод Зейделя:")
    print("   Количество итераций:", seidel_method(A, b, eps)[1])
    print("   ||x - x_a||:", np.linalg.norm(x - seidel_method(A, b, eps)[0]))
    print("----------------------------------------------------------------------------------------------")

Матрица из методички А.Н.Пакулиной:
[20.  3. -1.]
[ 1. 50.  1.]
[ 1.  3. 40.]
Погрешность: 0.0001
Методе простой итерации:
   Количество итераций: 6
   ||x - x_a||: 2.4432448351772964e-07

Метод Зейделя:
   Количество итераций: 5
   ||x - x_a||: 8.584621572700049e-08
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[20.  3. -1.]
[ 1. 50.  1.]
[ 1.  3. 40.]
Погрешность: 1e-07
Методе простой итерации:
   Количество итераций: 9
   ||x - x_a||: 4.2180655997287734e-11

Метод Зейделя:
   Количество итераций: 6
   ||x - x_a||: 3.431701589326068e-10
----------------------------------------------------------------------------------------------
Матрица из методички А.Н.Пакулиной:
[20.  3. -1.]
[ 1. 50.  1.]
[ 1.  3. 40.]
Погрешность: 1e-10
Методе простой итерации:
   Количество итераций: 11
   ||x - x_a||: 1.4228607195221903e-13

Метод Зейделя:
   Количество итераций: 8
   ||x - x_a||: 1.5888218580782548e-14
------