In [59]:
import numpy as np
import pandas as pd
from math import sqrt

In [60]:
def find_b(L, x):  # находим b
    b = np.dot(L, x)
    return b

In [61]:
def solve(L, b):  # решаем регуляризационную систему
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(L.transpose(), y)
    return x


In [62]:
def sqrt_method(A):  # метод квадратого корня
    L = np.zeros((A.shape[0], A.shape[0]))
    for i in range(A.shape[0]):
        for j in range(i):
            temp = 0
            for k in range(j):
                temp += L[i][k] * L[j][k]
            L[i][j] = (A[i][j] - temp) / L[j][j]
        temp = A[i][i]
        for k in range(i):
            temp -= L[i][k] * L[i][k]
        L[i][i] = sqrt(temp)
    return L


In [63]:
def variation_matrix(A, alpha, b, x):
    df.append([alpha, np.linalg.cond(A), np.linalg.cond(A + alpha * np.eye(A.shape[0])),
                 np.linalg.norm(x - solve(sqrt_method(A + alpha * np.eye(A.shape[0])), b))])
    return df

In [64]:
def print_all(A, df, alpha, diff_matr):
    print("Матрица:")
    print(*A, sep='\n')
    print()
    print(pd.DataFrame(df, columns = ['alpha', 'cond(A)', 'cond(A+alpha*E)', '||x-x_a||']))
    print()
    print("||x - x_a|| для различных матриц:")
    print(pd.DataFrame(diff_matr, columns = ['Ax=b', 'A+alpha*x=b', 'A+10*alpha*x=b', 'A+0.1*alpha*x=b']))
    print()

In [65]:
data_Hilbert3 = [[1.0000, 0.5000, 0.3333],
                 [0.5000, 0.3333, 0.2500],
                 [0.3333, 0.2500, 0.2000]]
data_Hilbert4 = [[1.0000, 0.5000, 0.3333, 0.2500],
                 [0.5000, 0.3333, 0.2500, 0.2000],
                 [0.3333, 0.2500, 0.2000, 0.1667],
                 [0.2500, 0.2000, 0.1667, 0.1429]]
data_Hilbert5 = [[1.0000, 0.5000, 0.3333, 0.2500, 0.2000],
                 [0.5000, 0.3333, 0.2500, 0.2000, 0.1667],
                 [0.3333, 0.2500, 0.2000, 0.1667, 0.1429],
                 [0.2500, 0.2000, 0.1667, 0.1429, 0.1250],
                 [0.2000, 0.1667, 0.1429, 0.1250, 0.1111]]

In [66]:
A = np.array(data_Hilbert3, dtype=float)
x = np.ones(A.shape[0])
b = find_b(A, x)
df = []
for i in (-2, -4, -6, -8, -10, -12):
    variation_matrix(A, 10 ** i, b, x)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
min_diff = df[0][3]
for i in range(len(df)):
    if min_diff > df[i][3]:
        min_diff = df[i][3]
        alpha = df[i][0]
diff_matr = [[np.linalg.norm(x - solve(sqrt_method(A), b)),
              np.linalg.norm(x - solve(sqrt_method(A + alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 10 * alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 0.1 * alpha * np.eye(A.shape[0])), b))]]
print_all(A, df, alpha, diff_matr)

Матрица:
[1.     0.5    0.3333]
[0.5    0.3333 0.25  ]
[0.3333 0.25   0.2   ]

          alpha     cond(A)  cond(A+alpha*E)     ||x-x_a||
0  1.000000e-02  528.540912       111.989793  9.456109e-02
1  1.000000e-04  528.540912       509.458182  3.744172e-03
2  1.000000e-06  528.540912       528.342997  3.880585e-05
3  1.000000e-08  528.540912       528.538932  3.882000e-07
4  1.000000e-10  528.540912       528.540892  3.882009e-09
5  1.000000e-12  528.540912       528.540912  3.883995e-11

||x - x_a|| для различных матриц:
           Ax=b   A+alpha*x=b  A+10*alpha*x=b  A+0.1*alpha*x=b
0  1.834095e-12  3.788405e-09    3.786359e-08     3.791848e-10



In [67]:
pd.DataFrame(df, columns = ['alpha', 'cond(A)', 'cond(A + alpha * E)', '||x - x_a||'])

alpha     cond(A)  cond(A + alpha * E)   ||x - x_a||
0  1.000000e-02  528.540912           111.989793  9.456109e-02
1  1.000000e-04  528.540912           509.458182  3.744172e-03
2  1.000000e-06  528.540912           528.342997  3.880585e-05
3  1.000000e-08  528.540912           528.538932  3.882000e-07
4  1.000000e-10  528.540912           528.540892  3.882009e-09
5  1.000000e-12  528.540912           528.540912  3.883995e-11

In [68]:
A = np.array(data_Hilbert4, dtype=float)
x = np.ones(A.shape[0])
b = find_b(A, x)
df = []
for i in (-2, -4, -6, -8, -10, -12):
    variation_matrix(A, 10 ** i, b, x)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
min_diff = df[0][3]
for i in range(len(df)):
    if min_diff > df[i][3]:
        min_diff = df[i][3]
        alpha = df[i][0]
diff_matr = [[np.linalg.norm(x - solve(sqrt_method(A), b)),
              np.linalg.norm(x - solve(sqrt_method(A + alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 10 * alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 0.1 * alpha * np.eye(A.shape[0])), b))]]
print_all(A, df, alpha, diff_matr)

Матрица:
[1.     0.5    0.3333 0.25  ]
[0.5    0.3333 0.25   0.2   ]
[0.3333 0.25   0.2    0.1667]
[0.25   0.2    0.1667 0.1429]

          alpha       cond(A)  cond(A+alpha*E)     ||x-x_a||
0  1.000000e-02  19808.079661       149.884681  1.170389e-01
1  1.000000e-04  19808.079661      8537.195610  1.300110e-02
2  1.000000e-06  19808.079661     19549.962232  2.928614e-04
3  1.000000e-08  19808.079661     19805.464751  2.966582e-06
4  1.000000e-10  19808.079661     19808.053509  2.967039e-08
5  1.000000e-12  19808.079661     19808.079400  2.941382e-10

||x - x_a|| для различных матриц:
           Ax=b   A+alpha*x=b  A+10*alpha*x=b  A+0.1*alpha*x=b
0  5.367630e-11  2.847806e-07        0.000003     2.850012e-08



In [69]:
A = np.array(data_Hilbert5, dtype=float)
x = np.ones(A.shape[0])
b = find_b(A, x)
df = []
for i in (-2, -4, -6, -8, -10, -12):
    variation_matrix(A, 10 ** i, b, x)
x = np.random.uniform(0, 100, size=A.shape[0])
b = find_b(A, x)
min_diff = df[0][3]
for i in range(len(df)):
    if min_diff > df[i][3]:
        min_diff = df[i][3]
        alpha = df[i][0]
diff_matr = [[np.linalg.norm(x - solve(sqrt_method(A), b)),
              np.linalg.norm(x - solve(sqrt_method(A + alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 10 * alpha * np.eye(A.shape[0])), b)),
              np.linalg.norm(x - solve(sqrt_method(A + 0.1 * alpha * np.eye(A.shape[0])), b))]]
print_all(A, df, alpha, diff_matr)

Матрица:
[1.     0.5    0.3333 0.25   0.2   ]
[0.5    0.3333 0.25   0.2    0.1667]
[0.3333 0.25   0.2    0.1667 0.1429]
[0.25   0.2    0.1667 0.1429 0.125 ]
[0.2    0.1667 0.1429 0.125  0.1111]

          alpha        cond(A)  cond(A+alpha*E)     ||x-x_a||
0  1.000000e-02  137225.870896       157.524847  1.304298e-01
1  1.000000e-04  137225.870896     14065.290924  1.132977e-02
2  1.000000e-06  137225.870896    126176.701964  1.677773e-04
3  1.000000e-08  137225.870896    137105.808620  1.712636e-06
4  1.000000e-10  137225.870896    137224.669232  1.712650e-08
5  1.000000e-12  137225.870896    137225.858879  1.723123e-10

||x - x_a|| для различных матриц:
           Ax=b  A+alpha*x=b  A+10*alpha*x=b  A+0.1*alpha*x=b
0  1.307864e-10     0.000003        0.000028     2.766404e-07

