In [1]:
import numpy as np

In [2]:
def power_method(A, eps):
    x_0 = np.array(np.ones(A.shape[0]))
    lamb = 0
    iter = 0
    while True:
        iter += 1
        x_1 = np.dot(A, x_0)
        if abs(x_1[0] / x_0[0] - lamb) < eps:
            lamb = x_1[0] / x_0[0]
            break
        lamb = x_1[0] / x_0[0]
        x_0 = x_1
    return lamb, iter

In [3]:
def scal_method(A, eps):
    x_0 = np.array(np.ones(A.shape[0]))
    y_0 = np.array(np.ones(A.shape[0]))
    lamb = 0
    iter = 0
    while True:
        iter += 1
        x_1 = np.dot(A, x_0)
        y_1 = np.dot(A.T, y_0)
        if abs(np.dot(x_1, y_1) / np.dot(x_0, y_1) - lamb) < eps:
            lamb = np.dot(x_1, y_1) / np.dot(x_0, y_1)
            break
        lamb = np.dot(x_1, y_1) / np.dot(x_0, y_1)
        x_0 = x_1
        y_0 = y_1
    return lamb, iter

In [5]:
for n in (2, 3, 4, 5):
    A = np.array(np.zeros((n, n)), dtype=float)
    for i in range(n):
        for j in range(n):
            A[i][j] = 1 / (i + 1 + j)
    lambda_acc = max(abs(np.linalg.eig(A)[0]))
    for eps in (1e-2, 1e-3, 1e-4, 1e-5):
        print("Матрица:")
        print(*A, sep='\n')
        print("Погрешность:", eps)
        print("Степенной метод:")
        print("    Количество итераций:", power_method(A, eps)[1])
        print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(power_method(A, eps)[0])))
        print()
        print("Метод скалярных произведений:")
        print("    Количество итераций:", scal_method(A, eps)[1])
        print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(scal_method(A, eps)[0])))
        print("------------------------------------------------------------------------------------------")

Матрица:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 0.01
Степенной метод:
    Количество итераций: 3
    |lambda_acc - lambda|: 0.0005240627849874002

Метод скалярных произведений:
    Количество итераций: 2
    |lambda_acc - lambda|: 1.5369732005110492e-05
------------------------------------------------------------------------------------------
Матрица:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 0.001
Степенной метод:
    Количество итераций: 4
    |lambda_acc - lambda|: 2.7168375049457794e-05

Метод скалярных произведений:
    Количество итераций: 3
    |lambda_acc - lambda|: 4.134200626282336e-08
------------------------------------------------------------------------------------------
Матрица:
[1.  0.5]
[0.5        0.33333333]
Погрешность: 0.0001
Степенной метод:
    Количество итераций: 5
    |lambda_acc - lambda|: 1.4090104469843823e-06

Метод скалярных произведений:
    Количество итераций: 3
    |lambda_acc - lambda|: 4.134200626282336e-08
-----------------------------

In [6]:
data_1 = [[-5.509882, 1.870086, 0.422908],
             [0.287865, -11.811654, 5.7119],
             [0.049099, 4.308033, -12.970687]]
data_2 = [[-1.00449, -0.38726, 0.59047],
             [0.38726, 0.73999, 0.12519],
             [0.59047, 0.12519, -1.08660]]


In [7]:
A = np.array(data_1, dtype=float)
lambda_acc = max(abs(np.linalg.eig(A)[0]))
for eps in (1e-2, 1e-3, 1e-4, 1e-5):
    print("Матрица:")
    print(*A, sep='\n')
    print("Погрешность:", eps)
    print("Степенной метод:")
    print("    Количество итераций:", power_method(A, eps)[1])
    print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(power_method(A, eps)[0])))
    print()
    print("Метод скалярных произведений:")
    print("    Количество итераций:", scal_method(A, eps)[1])
    print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(scal_method(A, eps)[0])))
    print("------------------------------------------------------------------------------------------")

Матрица:
[-5.509882  1.870086  0.422908]
[  0.287865 -11.811654   5.7119  ]
[  0.049099   4.308033 -12.970687]
Погрешность: 0.01
Степенной метод:
    Количество итераций: 15
    |lambda_acc - lambda|: 0.005241572527062033

Метод скалярных произведений:
    Количество итераций: 8
    |lambda_acc - lambda|: 0.0021323845301530753
------------------------------------------------------------------------------------------
Матрица:
[-5.509882  1.870086  0.422908]
[  0.287865 -11.811654   5.7119  ]
[  0.049099   4.308033 -12.970687]
Погрешность: 0.001
Степенной метод:
    Количество итераций: 18
    |lambda_acc - lambda|: 0.00044042671637711805

Метод скалярных произведений:
    Количество итераций: 10
    |lambda_acc - lambda|: 7.63606130256278e-05
------------------------------------------------------------------------------------------
Матрица:
[-5.509882  1.870086  0.422908]
[  0.287865 -11.811654   5.7119  ]
[  0.049099   4.308033 -12.970687]
Погрешность: 0.0001
Степенной метод:
    Колич

In [8]:
A = np.array(data_2, dtype=float)
lambda_acc = max(abs(np.linalg.eig(A)[0]))
for eps in (1e-2, 1e-3, 1e-4, 1e-5):
    print("Матрица:")
    print(*A, sep='\n')
    print("Погрешность:", eps)
    print("Степенной метод:")
    print("    Количество итераций:", power_method(A, eps)[1])
    print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(power_method(A, eps)[0])))
    print()
    print("Метод скалярных произведений:")
    print("    Количество итераций:", scal_method(A, eps)[1])
    print("    |lambda_acc - lambda|:", abs(lambda_acc - abs(scal_method(A, eps)[0])))
    print("------------------------------------------------------------------------------------------")

Матрица:
[-1.00449 -0.38726  0.59047]
[0.38726 0.73999 0.12519]
[ 0.59047  0.12519 -1.0866 ]
Погрешность: 0.01
Степенной метод:
    Количество итераций: 12
    |lambda_acc - lambda|: 0.0017083010687521938

Метод скалярных произведений:
    Количество итераций: 8
    |lambda_acc - lambda|: 0.0006818349182877714
------------------------------------------------------------------------------------------
Матрица:
[-1.00449 -0.38726  0.59047]
[0.38726 0.73999 0.12519]
[ 0.59047  0.12519 -1.0866 ]
Погрешность: 0.001
Степенной метод:
    Количество итераций: 14
    |lambda_acc - lambda|: 0.00027408666925077263

Метод скалярных произведений:
    Количество итераций: 9
    |lambda_acc - lambda|: 0.00010984759850996006
------------------------------------------------------------------------------------------
Матрица:
[-1.00449 -0.38726  0.59047]
[0.38726 0.73999 0.12519]
[ 0.59047  0.12519 -1.0866 ]
Погрешность: 0.0001
Степенной метод:
    Количество итераций: 17
    |lambda_acc - lambda|: 1.7662